name: tencent_cos_plus
description: A powerful tencent cos plugin, support bucket and object basic api.
version: 1.2.2
homepage: https://github.com/TryImpossible/flutter-plugins/tree/main/packages/tencent_cos_plus
repository: https://github.com/TryImpossible/flutter-plugins/tree/main/packages/tencent_cos_plus
issue_tracker: https://github.com/TryImpossible/flutter-plugins/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # https://pub.flutter-io.cn/packages/path
  path: ^1.8.3
  # https://pub.flutter-io.cn/packages/http
  http: ^1.0.0
  # https://pub.flutter-io.cn/packages/http_parser
  http_parser: ^4.0.2
  # https://pub.flutter-io.cn/packages/mime
  mime: ^1.0.4
  # https://pub.flutter-io.cn/packages/html
  html: ^0.15.4
  # https://pub.flutter-io.cn/packages/crypto
  crypto: ^3.0.3
  # https://pub.flutter-io.cn/packages/xml
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
